# Generated by Django 5.0.6 on 2024-10-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pic.png', upload_to='profile_pictures'),
        ),
    ]
