# Generated by Django 5.0.6 on 2024-10-24 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_item_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='username',
            new_name='user_name',
        ),
    ]
