# Generated by Django 5.0.6 on 2024-10-25 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0019_alter_item_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='user_name',
            new_name='user',
        ),
    ]
